const colors = require('tailwindcss/colors')
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
    purge: [],
    theme: {
        fontFamily: {
            body:            ['Inter',          ...defaultTheme.fontFamily.sans],
            'header':        ['Archia-Regular', ...defaultTheme.fontFamily.sans],
            'header-medium': ['Archia-Medium',  ...defaultTheme.fontFamily.sans],
            'header-light':  ['Archia-Light',   ...defaultTheme.fontFamily.sans],
            'header-thin':   ['Archia-Thin',    ...defaultTheme.fontFamily.sans],
        },
        colors: {
            transparent: 'transparent',
            current: 'currentColor',
            black: colors.black,
            white: colors.white,
            gray: colors.coolGray,
            red: colors.red,
            teal: colors.teal,
            rose: colors.rose,
            yellow: colors.amber,
            orange: colors.orange,
            blue: colors.blue,
            pink: colors.pink,
        },
        borderWidth: {
            DEFAULT: '1px',
            '0': '0',
            '2': '2px',
            '3': '3px',
            '4': '4px',
            '6': '6px',
            '8': '8px',
        },
        borderRadius: {
            none: '0',
            sm: '.125rem',
            DEFAULT: '.25rem',
            lg: '.5rem',
            full: '9999px',
            xl: '1rem',
            '2xl': '1.25rem',
        },
        screens: {
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1200px',
        },
        opacity: {
            '5': '.05',
            '10': '.1',
            '20': '.2',
            '30': '.3',
            '40': '.4',
            '50': '.5',
            '60': '.6',
            '70': '.7',
            '80': '.8',
            '90': '.9',
            '100': '1',
        },
        zIndex: {
            '0': 0,
            '100': 100,
            '150': 150,
            '200': 200,
            '250': 250,
            '300': 300,
            '350': 350,
            '400': 400,
            '450': 450,
            '500': 500,
            '550': 550,
            '600': 600,
            '650': 650,
            '700': 700,
            '750': 750,
            '800': 800,
            '850': 850,
            '900': 900,
            '950': 950,
            '1000': 1000,
            auto: 'auto',
        },
        extend: {
            boxShadow: {
                header: '4px 4px 12px 0px rgba(0,0,0,0.04)',
            },
            height: {
                nav: '70px',
                search: '60px',
                'search-form': '40px',
            },
            spacing: {
                7: '1.75rem',
                '72': '18rem',
                '84': '21rem',
                '96': '24rem',
            },
            colors: {
                white: '#FFFFFF',
                black: '#3F3F46',
                primary: '#AF5998',
                'primary-accent': '#B96EA5',
                secondary: '#1693A5',
                'secondary-accent': '#19A8BD',
                'gray-1': '#F5F7FA',
                'gray-2': '#CBD5E0',
                'gray-3': '#4A5568',
            },
        },
    },
    variants: {
        padding: ['responsive', 'first'],
        textColor: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
        tableLayout: ['responsive', 'hover', 'focus'],
        borderColor: ['responsive', 'hover', 'focus', 'focus-within', 'group-hover'],
        backgroundColor: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
    },
    plugins: []
};